name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Mv to folder
      run: |-
        cd IncidenciaAreas
    - name: Fetch latest data
      run: |-
        curl -f "https://coronavirus.sergas.es/infodatos/"`date "+%Y-%m-%d"`"_COVID19_Web_CifrasTotais.csv" -o `date "+%Y-%m-%d"`"_CifrasTotales.csv"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add `date "+%Y-%m-%d"`"_CifrasTotales.csv"
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
